
[AtCoder]
  ContestID = "abc074"
  ContestURL = "https://atcoder.jp/contests/abc074"
  TaskID = "arc083_b"
  TaskName = "D - Restoring Road Network"
  TaskURL = "https://atcoder.jp/contests/abc074/tasks/arc083_b"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
