
[AtCoder]
  ContestID = "abc065"
  ContestURL = "https://atcoder.jp/contests/abc065"
  TaskID = "arc076_b"
  TaskName = "D - Built?"
  TaskURL = "https://atcoder.jp/contests/abc065/tasks/arc076_b"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
