
[AtCoder]
  ContestID = "abc153"
  ContestURL = "https://atcoder.jp/contests/abc153"
  TaskID = "abc153_e"
  TaskName = "E - Crested Ibis vs Monster"
  TaskURL = "https://atcoder.jp/contests/abc153/tasks/abc153_e"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
