
[AtCoder]
  ContestID = "abc012"
  ContestURL = "https://abc012.contest.atcoder.jp/"
  TaskID = "abc012_d"
  TaskName = "D - バスと避けられない運命"
  TaskURL = "https://abc012.contest.atcoder.jp/tasks/abc012_4"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
