
[AtCoder]
  ContestID = "abc015"
  ContestURL = "https://atcoder.jp/contests/abc015"
  TaskID = "abc015_4"
  TaskName = "D - 高橋くんの苦悩"
  TaskURL = "https://atcoder.jp/contests/abc015/tasks/abc015_4"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
