
[AtCoder]
  ContestID = "abc091"
  ContestURL = "https://atcoder.jp/contests/abc091"
  TaskID = "arc092_b"
  TaskName = "D - Two Sequences"
  TaskURL = "https://atcoder.jp/contests/abc091/tasks/arc092_b"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
