
[AtCoder]
  ContestID = "abc030"
  ContestURL = "https://atcoder.jp/contests/abc030"
  TaskID = "abc030_b"
  TaskName = "B - 時計盤"
  TaskURL = "https://atcoder.jp/contests/abc030/tasks/abc030_b"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
