
[AtCoder]
  ContestID = "abc082"
  ContestURL = "https://atcoder.jp/contests/abc082"
  TaskID = "abc082_a"
  TaskName = "A - Round Up the Mean"
  TaskURL = "https://atcoder.jp/contests/abc082/tasks/abc082_a"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
