
[AtCoder]
  ContestID = "abc020"
  ContestURL = "https://atcoder.jp/contests/abc020"
  TaskID = "abc020_d"
  TaskName = "D - LCM Rush"
  TaskURL = "https://atcoder.jp/contests/abc020/tasks/abc020_d"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
