
[AtCoder]
  ContestID = "code-festival-2016-qualb"
  ContestURL = "https://atcoder.jp/contests/code-festival-2016-qualb"
  TaskID = "codefestival_2016_qualB_e"
  TaskName = "E - Lexicographical disorder"
  TaskURL = "https://atcoder.jp/contests/code-festival-2016-qualb/tasks/codefestival_2016_qualB_e"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
