
[AtCoder]
  ContestID = "abc104"
  ContestURL = "https://atcoder.jp/contests/abc104"
  TaskID = "abc104_c"
  TaskName = "C - All Green"
  TaskURL = "https://atcoder.jp/contests/abc104/tasks/abc104_c"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
