
[AtCoder]
  ContestID = "abc167"
  ContestURL = "https://atcoder.jp/contests/abc167"
  TaskID = "abc167_f"
  TaskName = "F - Bracket Sequencing"
  TaskURL = "https://atcoder.jp/contests/abc167/tasks/abc167_f"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
